cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.2604901
  brandStrength: 1
  lightness: 0
  brandColors:
    - '#150E0D'
    - '#FFFFFF'
    - '#BDB4B3'
    - '#916F4A'
    - '#FB064A'
  rhythmicContrast: 0.3723404
typography_spectrum: 0.393617
layout_spectrum: 0.2170213
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: PETRI NAUHA
