name: PETRI NAUHA
favicon: null
layout_spectrum: 0.8371630108449608
typography_spectrum: 0.49614176573231816
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.1909898747690022
  lightness: 0.897674762411043
  saturation: 0.26049008895643055
  rhythmicContrast: 0.05228514550253749
purpose: []
