name: PETRI NAUHA
favicon: null
layout_spectrum: 0.2170213
typography_spectrum: 0.393617
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: PETRI NAUHA
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#150E0D'
    - '#FFFFFF'
    - '#BDB4B3'
    - '#916F4A'
    - '#FB064A'
  brandStrength: 1
  lightness: 0
  saturation: 0.2604901
  rhythmicContrast: 0.3723404
purpose: []
